language: python
services:
- docker

before_script:
- echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- "./ci/build.sh"

deploy:
- provider: script
  script: bash ./ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master